import type { DataBlockDef } from './dynamic_page.seed.types';

// Data-driven block definitions — each wires a client script to a server
// handler that reads/writes a CMS collection. Unique key is (tenantId, type).
export const dataBlockDefs: DataBlockDef[] = [
  // Blog List block: fetches the posts collection via its server handler.
  {
    type: 'blog-list',
    label: 'Blog List',
    category: 'Content',
    description: 'Renders paginated posts from the "posts" collection.',
    schema: {
      properties: {
        limit: { type: 'number', title: 'Posts per page' },
        heading: { type: 'string', title: 'Section heading' },
      },
    },
    defaultProps: { limit: 6, heading: 'Latest Posts' },
    template: '<section class="blog-list"><h2>{{heading}}</h2><div id="blog-list-{{blockId}}"><p>Loading...</p></div></section>',
    script: [
      '(function() {',
      '  var ctx = window.__blockCtx && window.__blockCtx["blog-list"];',
      '  if (!ctx) return;',
      '  var container = document.getElementById("blog-list-{{blockId}}");',
      '  if (!container) return;',
      '  ctx.fetch("?limit={{limit}}")',
      '    .then(function(r) { return r.json(); })',
      '    .then(function(res) {',
      '      var items = (res.items || []);',
      '      container.innerHTML = items.map(function(i) {',
      '        return "<article><h3>" + (i.data.title || "") + "</h3><p>" + (i.data.excerpt || "") + "</p></article>";',
      '      }).join("") || "<p>No posts yet.</p>";',
      '    })',
      '    .catch(function() { container.innerHTML = "<p>Failed to load posts.</p>"; });',
      '})();',
    ].join('\n'),
    serverHandler: [
      'async function handler({ method, query, db, respond }) {',
      '  if (method !== "GET") return respond({ message: "Method not allowed" }, 405);',
      '  const limit = parseInt(query.limit || "6", 10);',
      '  const page = parseInt(query.page || "0", 10);',
      '  const result = await db.collection("posts").find({ limit, page, sort: "-createdAt" });',
      '  return respond(result);',
      '}',
    ].join('\n'),
    allowedCollections: ['posts'],
    isSystem: false,
  },
  // Lead Form block: saves submissions to the "leads" collection via its server handler.
  {
    type: 'lead-form',
    label: 'Lead Form',
    category: 'Marketing',
    description: 'Contact form that saves submissions to the "leads" collection.',
    schema: {
      properties: {
        heading: { type: 'string', title: 'Form heading' },
        submitLabel: { type: 'string', title: 'Submit button label' },
      },
    },
    defaultProps: { heading: 'Get in touch', submitLabel: 'Send message' },
    template: [
      '<section class="lead-form">',
      '  <h2>{{heading}}</h2>',
      '  <form id="lead-form-{{blockId}}">',
      '    <input name="name" placeholder="Full name" required />',
      '    <input name="email" type="email" placeholder="Email" required />',
      '    <input name="phone" placeholder="Phone (optional)" />',
      '    <textarea name="message" placeholder="Message"></textarea>',
      '    <button type="submit">{{submitLabel}}</button>',
      '    <p class="lead-form-status"></p>',
      '  </form>',
      '</section>',
    ].join('\n'),
    script: [
      '(function() {',
      '  var ctx = window.__blockCtx && window.__blockCtx["lead-form"];',
      '  if (!ctx) return;',
      '  var form = document.getElementById("lead-form-{{blockId}}");',
      '  if (!form) return;',
      '  form.addEventListener("submit", function(e) {',
      '    e.preventDefault();',
      '    var data = Object.fromEntries(new FormData(form));',
      '    ctx.fetch("", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ data: data }) })',
      '      .then(function(r) { return r.json(); })',
      '      .then(function() {',
      '        form.querySelector(".lead-form-status").textContent = "Thank you! We will be in touch.";',
      '        form.reset();',
      '      })',
      '      .catch(function() {',
      '        form.querySelector(".lead-form-status").textContent = "Something went wrong. Please try again.";',
      '      });',
      '  });',
      '})();',
    ].join('\n'),
    serverHandler: [
      'async function handler({ method, body, db, respond }) {',
      '  if (method !== "POST") return respond({ message: "Method not allowed" }, 405);',
      '  if (!body || !body.data) return respond({ message: "Missing data" }, 400);',
      '  var data = body.data;',
      '  if (!data.name || !data.email) return respond({ message: "name and email are required" }, 400);',
      '  var item = await db.collection("leads").create({ name: data.name, email: data.email, phone: data.phone || null, message: data.message || null });',
      '  return respond({ item }, 201);',
      '}',
    ].join('\n'),
    allowedCollections: ['leads'],
    isSystem: false,
  },
];
