// ============================================================================
// Module Registry (Auto-Generated)
// ============================================================================
// DO NOT EDIT THIS FILE MANUALLY!
// Generated by: scripts/generate-modules.ts
// Run: npm run generate:modules

import { ModuleJson } from './module.types';

// Import module.json from each discovered module
import aiModule from './ai/module.json';
import authModule from './auth/module.json';
import auth_ssoModule from './auth_sso/module.json';
import notification_mailModule from './notification_mail/module.json';
import notification_smsModule from './notification_sms/module.json';
import paymentModule from './payment/module.json';
import settingModule from './setting/module.json';
import storageModule from './storage/module.json';
import tenantModule from './tenant/module.json';
import tenant_brandingModule from './tenant_branding/module.json';
import tenant_domainModule from './tenant_domain/module.json';
import tenant_memberModule from './tenant_member/module.json';
import tenant_sessionModule from './tenant_session/module.json';
import tenant_settingModule from './tenant_setting/module.json';
import userModule from './user/module.json';
import user_agentModule from './user_agent/module.json';
import user_preferencesModule from './user_preferences/module.json';
import user_profileModule from './user_profile/module.json';
import user_securityModule from './user_security/module.json';
import user_sessionModule from './user_session/module.json';
import user_social_accountModule from './user_social_account/module.json';

// Module path mapping
export const MODULE_PATHS: Record<string, string> = {
  ai: '@/modules/ai',
  auth: '@/modules/auth',
  auth_sso: '@/modules/auth_sso',
  notification_mail: '@/modules/notification_mail',
  notification_sms: '@/modules/notification_sms',
  payment: '@/modules/payment',
  setting: '@/modules/setting',
  storage: '@/modules/storage',
  tenant: '@/modules/tenant',
  tenant_branding: '@/modules/tenant_branding',
  tenant_domain: '@/modules/tenant_domain',
  tenant_member: '@/modules/tenant_member',
  tenant_session: '@/modules/tenant_session',
  tenant_setting: '@/modules/tenant_setting',
  user: '@/modules/user',
  user_agent: '@/modules/user_agent',
  user_preferences: '@/modules/user_preferences',
  user_profile: '@/modules/user_profile',
  user_security: '@/modules/user_security',
  user_session: '@/modules/user_session',
  user_social_account: '@/modules/user_social_account',
};

// All registered modules
export const REGISTERED_MODULES: ModuleJson[] = [
  aiModule as ModuleJson,
  authModule as ModuleJson,
  auth_ssoModule as ModuleJson,
  notification_mailModule as ModuleJson,
  notification_smsModule as ModuleJson,
  paymentModule as ModuleJson,
  settingModule as ModuleJson,
  storageModule as ModuleJson,
  tenantModule as ModuleJson,
  tenant_brandingModule as ModuleJson,
  tenant_domainModule as ModuleJson,
  tenant_memberModule as ModuleJson,
  tenant_sessionModule as ModuleJson,
  tenant_settingModule as ModuleJson,
  userModule as ModuleJson,
  user_agentModule as ModuleJson,
  user_preferencesModule as ModuleJson,
  user_profileModule as ModuleJson,
  user_securityModule as ModuleJson,
  user_sessionModule as ModuleJson,
  user_social_accountModule as ModuleJson,
];

// ============================================================================
// Public API
// ============================================================================

export function getEnabledModules(): ModuleJson[] {
  return REGISTERED_MODULES
    .filter(m => m.enabled !== false)
    .sort((a, b) => (a.priority ?? 100) - (b.priority ?? 100));
}

export function getModuleById(id: string): ModuleJson | undefined {
  return REGISTERED_MODULES.find(m => m.id === id);
}

export function isModuleEnabled(id: string): boolean {
  const module = getModuleById(id);
  return module?.enabled !== false;
}

export function getModulePath(id: string): string {
  return MODULE_PATHS[id] || `@/modules/${id}`;
}

export function getModuleIds(): string[] {
  return REGISTERED_MODULES.map(m => m.id);
}
