
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.3.0
 * Query Engine version: 9d6ad21cbbceab97458517b147a6a09ff43aa735
 */
Prisma.prismaVersion = {
  client: "7.3.0",
  engine: "9d6ad21cbbceab97458517b147a6a09ff43aa735"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.PaymentScalarFieldEnum = {
  paymentId: 'paymentId',
  userId: 'userId',
  tenantId: 'tenantId',
  provider: 'provider',
  providerPaymentId: 'providerPaymentId',
  amount: 'amount',
  currency: 'currency',
  status: 'status',
  paymentMethod: 'paymentMethod',
  description: 'description',
  metadata: 'metadata',
  customerEmail: 'customerEmail',
  customerName: 'customerName',
  customerPhone: 'customerPhone',
  billingAddress: 'billingAddress',
  refundedAmount: 'refundedAmount',
  failureCode: 'failureCode',
  failureMessage: 'failureMessage',
  paidAt: 'paidAt',
  cancelledAt: 'cancelledAt',
  refundedAt: 'refundedAt',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.PaymentTransactionScalarFieldEnum = {
  transactionId: 'transactionId',
  paymentId: 'paymentId',
  provider: 'provider',
  providerTransactionId: 'providerTransactionId',
  type: 'type',
  status: 'status',
  amount: 'amount',
  currency: 'currency',
  fee: 'fee',
  net: 'net',
  providerResponse: 'providerResponse',
  errorCode: 'errorCode',
  errorMessage: 'errorMessage',
  parentTransactionId: 'parentTransactionId',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  processedAt: 'processedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SettingScalarFieldEnum = {
  key: 'key',
  value: 'value',
  group: 'group',
  type: 'type',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TenantScalarFieldEnum = {
  tenantId: 'tenantId',
  name: 'name',
  description: 'description',
  tenantStatus: 'tenantStatus',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.TenantDomainScalarFieldEnum = {
  tenantDomainId: 'tenantDomainId',
  tenantId: 'tenantId',
  domain: 'domain',
  isPrimary: 'isPrimary',
  domainStatus: 'domainStatus',
  verificationToken: 'verificationToken',
  verifiedAt: 'verifiedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TenantMemberScalarFieldEnum = {
  tenantMemberId: 'tenantMemberId',
  tenantId: 'tenantId',
  userId: 'userId',
  memberRole: 'memberRole',
  memberStatus: 'memberStatus',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.TenantSettingScalarFieldEnum = {
  tenantSettingId: 'tenantSettingId',
  tenantId: 'tenantId',
  key: 'key',
  value: 'value',
  group: 'group',
  type: 'type',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserScalarFieldEnum = {
  userId: 'userId',
  email: 'email',
  phone: 'phone',
  password: 'password',
  userRole: 'userRole',
  userStatus: 'userStatus',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.UserPreferencesScalarFieldEnum = {
  userPreferencesId: 'userPreferencesId',
  userId: 'userId',
  theme: 'theme',
  language: 'language',
  emailNotifications: 'emailNotifications',
  smsNotifications: 'smsNotifications',
  pushNotifications: 'pushNotifications',
  newsletter: 'newsletter',
  timezone: 'timezone',
  dateFormat: 'dateFormat',
  timeFormat: 'timeFormat',
  firstDayOfWeek: 'firstDayOfWeek',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserProfileScalarFieldEnum = {
  userProfileId: 'userProfileId',
  userId: 'userId',
  name: 'name',
  biography: 'biography',
  profilePicture: 'profilePicture',
  headerImage: 'headerImage',
  socialLinks: 'socialLinks',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserSecurityScalarFieldEnum = {
  userSecurityId: 'userSecurityId',
  userId: 'userId',
  otpMethods: 'otpMethods',
  otpSecret: 'otpSecret',
  otpBackupCodes: 'otpBackupCodes',
  lastLoginAt: 'lastLoginAt',
  lastLoginIp: 'lastLoginIp',
  lastLoginDevice: 'lastLoginDevice',
  failedLoginAttempts: 'failedLoginAttempts',
  lockedUntil: 'lockedUntil',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserSessionScalarFieldEnum = {
  userSessionId: 'userSessionId',
  userId: 'userId',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  deviceFingerprint: 'deviceFingerprint',
  userAgent: 'userAgent',
  ipAddress: 'ipAddress',
  sessionStatus: 'sessionStatus',
  otpVerifyNeeded: 'otpVerifyNeeded',
  sessionExpiry: 'sessionExpiry',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserSocialAccountScalarFieldEnum = {
  userSocialAccountId: 'userSocialAccountId',
  userId: 'userId',
  provider: 'provider',
  providerId: 'providerId',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  profilePicture: 'profilePicture',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.PaymentProvider = exports.$Enums.PaymentProvider = {
  STRIPE: 'STRIPE',
  PAYPAL: 'PAYPAL',
  IYZICO: 'IYZICO'
};

exports.PaymentStatus = exports.$Enums.PaymentStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED'
};

exports.PaymentMethod = exports.$Enums.PaymentMethod = {
  CREDIT_CARD: 'CREDIT_CARD',
  DEBIT_CARD: 'DEBIT_CARD',
  BANK_TRANSFER: 'BANK_TRANSFER',
  PAYPAL: 'PAYPAL',
  APPLE_PAY: 'APPLE_PAY',
  GOOGLE_PAY: 'GOOGLE_PAY',
  OTHER: 'OTHER'
};

exports.TransactionType = exports.$Enums.TransactionType = {
  PAYMENT: 'PAYMENT',
  REFUND: 'REFUND',
  CHARGEBACK: 'CHARGEBACK',
  PAYOUT: 'PAYOUT'
};

exports.TransactionStatus = exports.$Enums.TransactionStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

exports.TenantStatus = exports.$Enums.TenantStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  PENDING: 'PENDING',
  SUSPENDED: 'SUSPENDED',
  DELETED: 'DELETED',
  ARCHIVED: 'ARCHIVED'
};

exports.DomainStatus = exports.$Enums.DomainStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED'
};

exports.TenantMemberRole = exports.$Enums.TenantMemberRole = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  USER: 'USER'
};

exports.TenantMemberStatus = exports.$Enums.TenantMemberStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  PENDING: 'PENDING'
};

exports.UserRole = exports.$Enums.UserRole = {
  GUEST: 'GUEST',
  USER: 'USER',
  ADMIN: 'ADMIN'
};

exports.UserStatus = exports.$Enums.UserStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED'
};

exports.Theme = exports.$Enums.Theme = {
  LIGHT: 'LIGHT',
  DARK: 'DARK',
  SYSTEM: 'SYSTEM'
};

exports.Language = exports.$Enums.Language = {
  EN: 'EN',
  ES: 'ES',
  FR: 'FR',
  DE: 'DE',
  CN: 'CN',
  JP: 'JP'
};

exports.DateFormat = exports.$Enums.DateFormat = {
  DD_MM_YYYY: 'DD_MM_YYYY',
  MM_DD_YYYY: 'MM_DD_YYYY'
};

exports.TimeFormat = exports.$Enums.TimeFormat = {
  H24: 'H24',
  H12: 'H12'
};

exports.FirstDayOfWeek = exports.$Enums.FirstDayOfWeek = {
  MON: 'MON',
  SUN: 'SUN'
};

exports.OTPMethod = exports.$Enums.OTPMethod = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  TOTP_APP: 'TOTP_APP'
};

exports.SessionStatus = exports.$Enums.SessionStatus = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  REVOKED: 'REVOKED'
};

exports.SocialAccountProvider = exports.$Enums.SocialAccountProvider = {
  google: 'google',
  apple: 'apple',
  facebook: 'facebook',
  github: 'github',
  linkedin: 'linkedin',
  microsoft: 'microsoft',
  twitter: 'twitter',
  slack: 'slack',
  tiktok: 'tiktok',
  wechat: 'wechat',
  autodesk: 'autodesk'
};

exports.Prisma.ModelName = {
  Payment: 'Payment',
  PaymentTransaction: 'PaymentTransaction',
  Setting: 'Setting',
  Tenant: 'Tenant',
  TenantDomain: 'TenantDomain',
  TenantMember: 'TenantMember',
  TenantSetting: 'TenantSetting',
  User: 'User',
  UserPreferences: 'UserPreferences',
  UserProfile: 'UserProfile',
  UserSecurity: 'UserSecurity',
  UserSession: 'UserSession',
  UserSocialAccount: 'UserSocialAccount'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
