// Renders the generated `module-components.ts` — a string-id → React.lazy map so
// manifest-referenced slot/widget components can be resolved at render time
// without each consumer hard-importing them. Consumed only by client code
// (the <Slot> component), so it lives under modules/common/ui/generated/.

export function renderComponentMap(componentImports) {
  const lines = componentImports.map(({ id, importPath, exportName }) => {
    // A contribution may be a default OR a named export (convention: named =
    // baseName). Cast the module to a loose record so accessing `.default` does
    // not error for modules that only have named exports.
    const pick = exportName
      ? `M.default ?? M[${JSON.stringify(exportName)}]`
      : 'M.default';
    return (
      `  ${JSON.stringify(id)}: lazy(() => import(${JSON.stringify(importPath)})` +
      `.then((m) => { const M = m as Record<string, ComponentType<any>>; return { default: ${pick} }; })),`
    );
  });
  return (
    `/* eslint-disable */\n` +
    `// AUTO-GENERATED by scripts/build-registry-snapshot.mjs. DO NOT EDIT.\n` +
    `import { lazy, type ComponentType } from 'react';\n\n` +
    `export const moduleComponents: Record<string, ComponentType<any>> = {\n` +
    (lines.length ? lines.join('\n') + '\n' : '') +
    `};\n`
  );
}
