// Renders the generated `module-components.ts` — a string-id → React.lazy map so
// manifest-referenced slot/widget components can be resolved at render time
// without each consumer hard-importing them. Consumed only by client code
// (the <Slot> component), so it lives under modules/common/ui/generated/.

export function renderComponentMap(componentImports) {
  const lines = componentImports.map(({ id, importPath, exportName }) => {
    const pick = exportName
      ? `m.default ?? m[${JSON.stringify(exportName)}]`
      : 'm.default';
    return `  ${JSON.stringify(id)}: lazy(() => import(${JSON.stringify(importPath)}).then((m) => ({ default: ${pick} }))),`;
  });
  return (
    `// AUTO-GENERATED by scripts/build-registry-snapshot.mjs. DO NOT EDIT.\n` +
    `import { lazy, type ComponentType } from 'react';\n\n` +
    `export const moduleComponents: Record<string, ComponentType<any>> = {\n` +
    (lines.length ? lines.join('\n') + '\n' : '') +
    `};\n`
  );
}
