import { z } from 'zod';

// Unlike z.coerce.boolean(), this treats "false"/"0" as false (coerce treats them as truthy).
export const boolEnv = () => z.preprocess(v => v === 'true' || v === '1', z.boolean());

// ── Secret field names used for redaction in error output ───────────────────
export const SECRET_KEYS = new Set([
  'ACCESS_TOKEN_SECRET', 'REFRESH_TOKEN_SECRET', 'CSRF_SECRET',
  'SMTP_PASS', 'MAILGUN_API_KEY', 'POSTMARK_API_KEY', 'SENDGRID_API_KEY',
  'RESEND_API_KEY', 'AWS_SES_SECRET_ACCESS_KEY', 'AWS_SECRET_ACCESS_KEY',
  'AWS_S3_SECRET_ACCESS_KEY', 'TWILIO_AUTH_TOKEN', 'NEXMO_API_SECRET',
  'CLICKATELL_API_KEY', 'NETGSM_PASSWORD', 'OPENAI_API_KEY', 'ANTHROPIC_API_KEY',
  'GOOGLE_AI_API_KEY', 'GOOGLE_CLIENT_SECRET', 'GITHUB_CLIENT_SECRET',
  'APPLE_PRIVATE_KEY', 'META_CLIENT_SECRET', 'MICROSOFT_CLIENT_SECRET',
  'AUTODESK_CLIENT_SECRET', 'LINKEDIN_CLIENT_SECRET', 'TIKTOK_CLIENT_SECRET',
  'TWITTER_CLIENT_SECRET', 'WECHAT_APP_SECRET', 'CRON_SECRET', 'DOTENV_KEY',
  'SETTINGS_ENCRYPTION_KEY', 'LOTL_SIGNER_CERT_PEM', 'MOBIL_IMZA_AGGREGATOR_API_KEY',
  'MOBIL_IMZA_CALLBACK_HMAC_SECRET', 'SMART_ID_RELYING_PARTY_UUID',
  'BANKID_SE_CLIENT_KEY_PATH', 'VAPID_PRIVATE_KEY', 'METRICS_SECRET',
  'ACS_PROVIDER_MAP', 'YANDEX_CLIENT_SECRET', 'VK_CLIENT_SECRET',
  'QQ_CLIENT_SECRET', 'WEIBO_CLIENT_SECRET', 'ALIPAY_PRIVATE_KEY',
]);
