#!/usr/bin/env ts-node
// ============================================================================
// Module Registry Generator
// ============================================================================
// Scans modules directory for module.json files and generates registry.ts
// Run: npx ts-node scripts/generate-modules.ts
// Or add to package.json: "prebuild": "ts-node scripts/generate-modules.ts"

import * as fs from 'fs';
import * as path from 'path';

const MODULES_DIR = path.join(__dirname, '../modules');
const OUTPUT_FILE = path.join(MODULES_DIR, 'registry.generated.ts');

interface ModuleInfo {
  id: string;
  folder: string;
  path: string;
}

function findModules(): ModuleInfo[] {
  const modules: ModuleInfo[] = [];

  const entries = fs.readdirSync(MODULES_DIR, { withFileTypes: true });

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;

    const moduleJsonPath = path.join(MODULES_DIR, entry.name, 'module.json');

    if (fs.existsSync(moduleJsonPath)) {
      try {
        const content = fs.readFileSync(moduleJsonPath, 'utf-8');
        const moduleJson = JSON.parse(content);

        modules.push({
          id: moduleJson.id || entry.name,
          folder: entry.name,
          path: `@/modules/${entry.name}`,
        });

        console.log(`  Found: ${entry.name} (${moduleJson.name || moduleJson.id})`);
      } catch (err) {
        console.error(`  Error reading ${moduleJsonPath}:`, err);
      }
    }
  }

  return modules;
}

function generateRegistry(modules: ModuleInfo[]): string {
  const imports = modules
    .map(m => `import ${m.folder}Module from './${m.folder}/module.json';`)
    .join('\n');

  const pathEntries = modules
    .map(m => `  ${m.id}: '${m.path}',`)
    .join('\n');

  const moduleEntries = modules
    .map(m => `  ${m.folder}Module as ModuleJson,`)
    .join('\n');

  return `// ============================================================================
// Module Registry (Auto-Generated)
// ============================================================================
// DO NOT EDIT THIS FILE MANUALLY!
// Generated by: scripts/generate-modules.ts
// Run: npm run generate:modules

import { ModuleJson } from './module.types';

// Import module.json from each discovered module
${imports}

// Module path mapping
export const MODULE_PATHS: Record<string, string> = {
${pathEntries}
};

// All registered modules
export const REGISTERED_MODULES: ModuleJson[] = [
${moduleEntries}
];

// ============================================================================
// Public API
// ============================================================================

export function getEnabledModules(): ModuleJson[] {
  return REGISTERED_MODULES
    .filter(m => m.enabled !== false)
    .sort((a, b) => (a.priority ?? 100) - (b.priority ?? 100));
}

export function getModuleById(id: string): ModuleJson | undefined {
  return REGISTERED_MODULES.find(m => m.id === id);
}

export function isModuleEnabled(id: string): boolean {
  const module = getModuleById(id);
  return module?.enabled !== false;
}

export function getModulePath(id: string): string {
  return MODULE_PATHS[id] || \`@/modules/\${id}\`;
}

export function getModuleIds(): string[] {
  return REGISTERED_MODULES.map(m => m.id);
}
`;
}

// Main
console.log('🔍 Scanning for modules...\n');
const modules = findModules();
console.log(`\n✅ Found ${modules.length} modules\n`);

const content = generateRegistry(modules);
fs.writeFileSync(OUTPUT_FILE, content, 'utf-8');
console.log(`📝 Generated: ${OUTPUT_FILE}\n`);
